---
title: "Workshop Modules"
---

::: {.panel-tabset}

## 1. Path Analysis

[View slides in full screen](slides/01-path_analysis.html)

```{=html}
<iframe class="slide-deck" src="slides/01-path_analysis.html" height="420" width="747" style="border: 1px solid #2e3846;"></iframe>
```

### Exercises

1. Run the R code in "note/data-exploration.R" to explore the data.
2. Fit the full path model using `we_data`:
   
   ```r
   model2 <- "
       NGSE ~ b1 * SOP
       PASS ~ b2 * NGSE + b3 * SOP
   "
   reg2 <- sem(model2, data = we_data)
   ```

3. Fit a restricted path model where the direct effect of `SOP` on `PASS` is removed:
   
   ```r
   model_restricted <- "
       NGSE ~ b1 * SOP
       PASS ~ b2 * NGSE
   "
   reg_restricted <- sem(model_restricted, data = we_data)
   ```
    
    What is the *p*-value from the likelihood ratio test comparing the two models, using the code below?
       
    ```r
    anova(reg2, reg_restricted)
    ```

## 2. Confirmatory Factor Analysis (CFA)

[View slides in full screen](slides/02-cfa.html)

```{=html}
<iframe class="slide-deck" src="slides/02-cfa.html" height="420" width="747" style="border: 1px solid #2e3846;"></iframe>
```

### Exercises

1. Run the R code in "note/data-exploration.R", and then the code in "note/cfa.R" to fit a CFA model.
    a. Which item has the highest standardized loading?
2. Fit the following modified CFA model:

   ```r
   model_1f_mod <- "
     SOP =~ SOP_1 + SOP_2 + SOP_3 + SOP_4 + SOP_5
     SOP_1 ~~ SOP_2
   "
   fit_1f_mod <- cfa(model_1f_mod, data = sop_data,
                     std.lv = TRUE, estimator = "MLR")
   ```

    a. How much did the fit improve in RMSEA and CFI?

3. Now try fitting a CFA model for the NGSE items:

   ```r
   ngse_data <- we_raw[, paste0("NGSE_", 1:8)]
   
   model_ngse <- "
     NGSE =~ NGSE_1 + NGSE_2 + NGSE_3 + NGSE_4 +
              NGSE_5 + NGSE_6 + NGSE_7 + NGSE_8
   "
   fit_ngse <- cfa(model_ngse, data = ngse_data,
                   std.lv = TRUE, estimator = "MLR", missing = "FIML")
   ```

    a. Check the loadings---are they all strong and positive?
    b. Inspect fit indices. Does the model fit well?
    c. Look at modification indices. Any theoretically motivated modifications?

## 3. Structural Regression Models (Full SEM)

[View slides in full screen](slides/03-structural.html)

```{=html}
<iframe class="slide-deck" src="slides/03-structural.html" height="420" width="747" style="border: 1px solid #2e3846;"></iframe>
```

### Exercises

1. Fit the measurement model using `we_data` and check fit.
    a. Which factor has the strongest average standardized loading?
2. Fit the structural mediation model without the direct path (c'):

   ```r
   model2_sr_we <- "
     SOP  =~ SOP_1 + SOP_2 + SOP_3 + SOP_4 + SOP_5
     NGSE =~ NGSE_1 + NGSE_2 + NGSE_3 + NGSE_4 +
             NGSE_5 + NGSE_6 + NGSE_7 + NGSE_8
     PASS =~ Pasgn + Pexam + Pread + Pgen

     NGSE ~ a * SOP
     PASS ~ b * NGSE

     indirect := a * b
   "
   fit2_sr_we <- sem(model2_sr_we, data = we_data,
                     std.lv = TRUE, estimator = "MLR", missing = "FIML")
   ```

    a. Compare fit to the model with the direct path:

    ```r
    anova(fit_sr_we, fit2_sr_we)
    ```

:::
