{
  "hash": "dd3854d8e1415fcfec82207beff79c81",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"CFA: Self-Oriented Perfectionism\"\nsubtitle: \"Data: Williams & Edwards (2021; OSF m5dy6)\"\n---\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(lavaan)\nlibrary(lavaangui)\nlibrary(psych)\nlibrary(dplyr)\nlibrary(semTools)\nlibrary(modelsummary)\nlibrary(tinytable)\n```\n:::\n\n\n\n\n## Dataset: Self-Oriented Perfectionism Scale (SOP)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwe_path <- here::here(\"data\", \"we_data.csv\")\nif (!file.exists(we_path)) {\n    download.file(\"https://osf.io/download/6mdb4/\", we_path)\n}\nwe_raw <- read.csv(we_path)\nwe_raw <- dplyr::rename(we_raw, Att_check = SOP_6)\n# Exclude: under-18, non-students, >6 missing study items, failed attention check, duplicates\nwe_vars <- c(\n    paste0(\"PASS_\", c(1:9, 16:18)),\n    paste0(\"NGSE_\", 1:8),\n    paste0(\"SOP_\",  1:5)\n)\nwe_raw <- we_raw[is.na(we_raw$Age) | we_raw$Age != 1, ]\nwe_raw <- we_raw[is.na(we_raw$Student) | we_raw$Student == 1, ]\nwe_raw$nmiss <- rowSums(is.na(we_raw[, we_vars]))\nwe_raw <- we_raw[we_raw$nmiss <= 6, ]\nwe_raw <- we_raw[!is.na(we_raw$Att_check) & we_raw$Att_check == 5, ]\nwe_raw <- we_raw[!duplicated(we_raw$PID_deID), ]\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsop_data <- we_raw[, paste0(\"SOP_\", 1:5)]\nnrow(sop_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 575\n```\n\n\n:::\n:::\n\n\nThis example uses data from a conceptual replication of Seo (2008), examining self-efficacy as a mediator between self-oriented perfectionism and academic procrastination (Williams & Edwards, 2021; OSF: [osf.io/m5dy6](https://osf.io/m5dy6/)).\n\nWe focus here on the **SOP** subscale, which measures **self-oriented perfectionism**---the tendency to set high personal standards and be self-critical when those standards are not met:\n\n| Items | Content |\n|-------|---------|\n| SOP_1–SOP_5 | Self-oriented perfectionism (5 items) |\n\nItems use a **5-point Likert scale**. The scale is theoretically **unidimensional**: all five items reflect a single latent construct. Data were collected online (Prolific Academic); *N* = 623 recruited.\n\n::: {.callout-note}\n## Data Cleaning\n\nFollowing the preregistered exclusion criteria:\n\n1. Non-students or participants under 18 were excluded.\n2. Participants missing more than 6 items across the three main scales (PASS, NGSE, SOP) were excluded.\n3. Participants who failed the attention check (SOP_6; correct response = 5) were excluded.\n4. Duplicate Prolific IDs were removed.\n\nThe `load-data` chunk above applies all four criteria, reducing the sample to approximately *N* = 480.\n:::\n\n### Descriptive Statistics\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelsummary::datasummary_skim(sop_data)\n```\n\n::: {.cell-output-display}\n\n```{=typst}\n#show figure: set block(breakable: true)\n\n#block[ // start block\n\n  #let style-dict = (\n    // tinytable style-dict after\n    \"0_0\": 0, \"1_0\": 0, \"2_0\": 0, \"3_0\": 0, \"4_0\": 0, \"5_0\": 0, \"0_1\": 0, \"1_1\": 0, \"2_1\": 0, \"3_1\": 0, \"4_1\": 0, \"5_1\": 0, \"0_2\": 0, \"1_2\": 0, \"2_2\": 0, \"3_2\": 0, \"4_2\": 0, \"5_2\": 0, \"0_3\": 0, \"1_3\": 0, \"2_3\": 0, \"3_3\": 0, \"4_3\": 0, \"5_3\": 0, \"0_4\": 0, \"1_4\": 0, \"2_4\": 0, \"3_4\": 0, \"4_4\": 0, \"5_4\": 0, \"0_5\": 0, \"1_5\": 0, \"2_5\": 0, \"3_5\": 0, \"4_5\": 0, \"5_5\": 0, \"0_6\": 0, \"1_6\": 0, \"2_6\": 0, \"3_6\": 0, \"4_6\": 0, \"5_6\": 0, \"0_7\": 0, \"1_7\": 0, \"2_7\": 0, \"3_7\": 0, \"4_7\": 0, \"5_7\": 0, \"0_8\": 0, \"1_8\": 0, \"2_8\": 0, \"3_8\": 0, \"4_8\": 0, \"5_8\": 0\n  )\n\n  #let style-array = ( \n    // tinytable cell style after\n    (align: left,),\n  )\n\n  // Helper function to get cell style\n  #let get-style(x, y) = {\n    let key = str(y) + \"_\" + str(x)\n    if key in style-dict { style-array.at(style-dict.at(key)) } else { none }\n  }\n\n  // tinytable align-default-array before\n  #let align-default-array = ( left, left, left, left, left, left, left, left, left, ) // tinytable align-default-array here\n  #show table.cell: it => {\n    if style-array.len() == 0 { return it }\n    \n    let style = get-style(it.x, it.y)\n    if style == none { return it }\n    \n    let tmp = it\n    if (\"fontsize\" in style) { tmp = text(size: style.fontsize, tmp) }\n    if (\"color\" in style) { tmp = text(fill: style.color, tmp) }\n    if (\"indent\" in style) { tmp = pad(left: style.indent, tmp) }\n    if (\"underline\" in style) { tmp = underline(tmp) }\n    if (\"italic\" in style) { tmp = emph(tmp) }\n    if (\"bold\" in style) { tmp = strong(tmp) }\n    if (\"mono\" in style) { tmp = math.mono(tmp) }\n    if (\"strikeout\" in style) { tmp = strike(tmp) }\n    if (\"smallcaps\" in style) { tmp = smallcaps(tmp) }\n    tmp\n  }\n\n  #align(center, [\n\n  #table( // tinytable table start\n    columns: (auto, auto, auto, auto, auto, auto, auto, auto, auto),\n    stroke: none,\n    rows: auto,\n    align: (x, y) => {\n      let style = get-style(x, y)\n      if style != none and \"align\" in style { style.align } else { left }\n    },\n    fill: (x, y) => {\n      let style = get-style(x, y)\n      if style != none and \"background\" in style { style.background }\n    },\n table.hline(y: 1, start: 0, end: 9, stroke: 0.05em + black),\n table.hline(y: 6, start: 0, end: 9, stroke: 0.08em + black),\n table.hline(y: 0, start: 0, end: 9, stroke: 0.08em + black),\n    // tinytable lines before\n\n    // tinytable header start\n    table.header(\n      repeat: true,\n[ ], [Unique], [Missing Pct.], [Mean], [SD], [Min], [Median], [Max], [Histogram],\n    ),\n    // tinytable header end\n\n    // tinytable cell content after\n[SOP\\_1], [5], [0], [3.5], [1.1], [1.0], [4.0], [5.0], [#image(\"tinytable_assets/tinytable_1_idyl89cy79t15596kfflil.png\", height: 1em)],\n[SOP\\_2], [5], [0], [3.3], [1.2], [1.0], [3.0], [5.0], [#image(\"tinytable_assets/tinytable_2_idqgqj107e0atssa1h2qtu.png\", height: 1em)],\n[SOP\\_3], [5], [0], [3.0], [1.1], [1.0], [3.0], [5.0], [#image(\"tinytable_assets/tinytable_3_idggq2ftrmgb50i897owgd.png\", height: 1em)],\n[SOP\\_4], [5], [0], [3.0], [1.2], [1.0], [3.0], [5.0], [#image(\"tinytable_assets/tinytable_4_id1i2f9yxjohu9kfhc3m7c.png\", height: 1em)],\n[SOP\\_5], [5], [0], [2.6], [1.2], [1.0], [2.0], [5.0], [#image(\"tinytable_assets/tinytable_5_ididqrl66jhe2d2svnuo9q.png\", height: 1em)],\n\n    // tinytable footer after\n\n  ) // end table\n\n  ]) // end align\n\n] // end block\n```\n\n:::\n:::\n\n\n### Inter-item Correlations\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnv <- ncol(sop_data)\ncor_sop <- cor(sop_data, use = \"pairwise.complete.obs\")\nbg <- rgb(as.integer(cor_sop > 0), 0, as.integer(cor_sop < 0),\n          alpha = abs(cor_sop))\nbg[upper.tri(cor_sop, diag = TRUE)] <- NA\nmodelsummary::datasummary_correlation(sop_data) |>\n  tinytable::style_tt(i = 1:nv, j = 1:nv + 1, background = bg)\n```\n\n::: {.cell-output-display}\n\n```{=typst}\n#show figure: set block(breakable: true)\n\n#block[ // start block\n\n  #let style-dict = (\n    // tinytable style-dict after\n    \"0_0\": 0, \"1_0\": 0, \"2_0\": 0, \"3_0\": 0, \"4_0\": 0, \"5_0\": 0, \"0_1\": 1, \"1_1\": 1, \"0_2\": 1, \"1_2\": 1, \"2_2\": 1, \"0_3\": 1, \"1_3\": 1, \"2_3\": 1, \"3_3\": 1, \"0_4\": 1, \"1_4\": 1, \"2_4\": 1, \"3_4\": 1, \"4_4\": 1, \"0_5\": 1, \"1_5\": 1, \"2_5\": 1, \"3_5\": 1, \"4_5\": 1, \"5_5\": 1, \"5_1\": 2, \"5_2\": 3, \"5_3\": 4, \"5_4\": 5, \"3_1\": 6, \"4_1\": 7, \"3_2\": 8, \"4_3\": 9, \"4_2\": 10, \"2_1\": 11\n  )\n\n  #let style-array = ( \n    // tinytable cell style after\n    (align: left,),\n    (align: right,),\n    (background: rgb(\"#FF000075\"), align: right,),\n    (background: rgb(\"#FF00008D\"), align: right,),\n    (background: rgb(\"#FF000092\"), align: right,),\n    (background: rgb(\"#FF00009B\"), align: right,),\n    (background: rgb(\"#FF0000AA\"), align: right,),\n    (background: rgb(\"#FF0000AD\"), align: right,),\n    (background: rgb(\"#FF0000AE\"), align: right,),\n    (background: rgb(\"#FF0000BC\"), align: right,),\n    (background: rgb(\"#FF0000C0\"), align: right,),\n    (background: rgb(\"#FF0000C4\"), align: right,),\n  )\n\n  // Helper function to get cell style\n  #let get-style(x, y) = {\n    let key = str(y) + \"_\" + str(x)\n    if key in style-dict { style-array.at(style-dict.at(key)) } else { none }\n  }\n\n  // tinytable align-default-array before\n  #let align-default-array = ( left, left, left, left, left, left, ) // tinytable align-default-array here\n  #show table.cell: it => {\n    if style-array.len() == 0 { return it }\n    \n    let style = get-style(it.x, it.y)\n    if style == none { return it }\n    \n    let tmp = it\n    if (\"fontsize\" in style) { tmp = text(size: style.fontsize, tmp) }\n    if (\"color\" in style) { tmp = text(fill: style.color, tmp) }\n    if (\"indent\" in style) { tmp = pad(left: style.indent, tmp) }\n    if (\"underline\" in style) { tmp = underline(tmp) }\n    if (\"italic\" in style) { tmp = emph(tmp) }\n    if (\"bold\" in style) { tmp = strong(tmp) }\n    if (\"mono\" in style) { tmp = math.mono(tmp) }\n    if (\"strikeout\" in style) { tmp = strike(tmp) }\n    if (\"smallcaps\" in style) { tmp = smallcaps(tmp) }\n    tmp\n  }\n\n  #align(center, [\n\n  #table( // tinytable table start\n    columns: (auto, auto, auto, auto, auto, auto),\n    stroke: none,\n    rows: auto,\n    align: (x, y) => {\n      let style = get-style(x, y)\n      if style != none and \"align\" in style { style.align } else { left }\n    },\n    fill: (x, y) => {\n      let style = get-style(x, y)\n      if style != none and \"background\" in style { style.background }\n    },\n table.hline(y: 1, start: 0, end: 6, stroke: 0.05em + black),\n table.hline(y: 6, start: 0, end: 6, stroke: 0.08em + black),\n table.hline(y: 0, start: 0, end: 6, stroke: 0.08em + black),\n    // tinytable lines before\n\n    // tinytable header start\n    table.header(\n      repeat: true,\n[ ], [SOP\\_1], [SOP\\_2], [SOP\\_3], [SOP\\_4], [SOP\\_5],\n    ),\n    // tinytable header end\n\n    // tinytable cell content after\n[SOP\\_1], [1], [.], [.], [.], [.],\n[SOP\\_2], [.77], [1], [.], [.], [.],\n[SOP\\_3], [.67], [.68], [1], [.], [.],\n[SOP\\_4], [.68], [.75], [.74], [1], [.],\n[SOP\\_5], [.46], [.55], [.57], [.61], [1],\n\n    // tinytable footer after\n\n  ) // end table\n\n  ]) // end align\n\n] // end block\n```\n\n:::\n:::\n\n\n::: {.callout-note}\nBlue cells = positive correlations, red = negative; intensity = magnitude. All five SOP items measure the same construct, so uniformly positive and moderately strong correlations are expected.\n:::\n\n### Dimensionality\n\n\n::: {.cell}\n\n```{.r .cell-code}\npsych::fa.parallel(sop_data, n.iter = 100,\n                   main = \"Parallel Analysis — SOP Items\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nParallel analysis suggests that the number of factors =  2  and the number of components =  1 \n```\n\n\n:::\n\n::: {.cell-output-display}\n![Scree plot with parallel analysis reference line.](cfa_files/figure-typst/fig-scree-1.svg){#fig-scree}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nev <- eigen(cor_sop, only.values = TRUE)$values\ndata.frame(\n  Factor        = seq_along(ev),\n  Eigenvalue    = round(ev, 3),\n  Cumulative_var = round(cumsum(ev) / sum(ev) * 100, 1)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Factor Eigenvalue Cumulative_var\n1      1      3.607           72.1\n2      2      0.582           83.8\n3      3      0.340           90.6\n4      4      0.269           96.0\n5      5      0.202          100.0\n```\n\n\n:::\n:::\n\n\n::: {.callout-note}\nParallel analysis for a unidimensional scale should retain exactly one factor. A dominant first eigenvalue well above the parallel analysis reference confirms that the five items share a single common cause.\n:::\n\n# Confirmatory Factor Analysis\n\n## Example 1: Single-Factor CFA\n\n[TODO: Identification strategies]\n\nBecause the SOP items are designed to reflect a single construct, we fit a **unidimensional (one-factor) CFA**. The latent factor variance is fixed to 1 (`std.lv = TRUE`) for identification, so all factor loadings are freely estimated.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_1f <- \"\n  SOP =~ SOP_1 + SOP_2 + SOP_3 + SOP_4 + SOP_5\n\"\nfit_1f <- cfa(model_1f, data = sop_data,\n              std.lv    = TRUE,\n              estimator = \"MLR\")\nsummary(fit_1f, fit.measures = TRUE, standardized = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nlavaan 0.6-21 ended normally after 17 iterations\n\n  Estimator                                         ML\n  Optimization method                           NLMINB\n  Number of model parameters                        10\n\n  Number of observations                           575\n\nModel Test User Model:\n                                              Standard      Scaled\n  Test Statistic                                68.758      45.706\n  Degrees of freedom                                 5           5\n  P-value (Chi-square)                           0.000       0.000\n  Scaling correction factor                                  1.504\n    Yuan-Bentler correction (Mplus variant)                       \n\nModel Test Baseline Model:\n\n  Test statistic                              1868.666    1238.181\n  Degrees of freedom                                10          10\n  P-value                                        0.000       0.000\n  Scaling correction factor                                  1.509\n\nUser Model versus Baseline Model:\n\n  Comparative Fit Index (CFI)                    0.966       0.967\n  Tucker-Lewis Index (TLI)                       0.931       0.934\n                                                                  \n  Robust Comparative Fit Index (CFI)                         0.967\n  Robust Tucker-Lewis Index (TLI)                            0.934\n\nLoglikelihood and Information Criteria:\n\n  Loglikelihood user model (H0)              -3639.962   -3639.962\n  Scaling correction factor                                  1.034\n      for the MLR correction                                      \n  Loglikelihood unrestricted model (H1)      -3605.583   -3605.583\n  Scaling correction factor                                  1.191\n      for the MLR correction                                      \n                                                                  \n  Akaike (AIC)                                7299.923    7299.923\n  Bayesian (BIC)                              7343.467    7343.467\n  Sample-size adjusted Bayesian (SABIC)       7311.721    7311.721\n\nRoot Mean Square Error of Approximation:\n\n  RMSEA                                          0.149       0.119\n  90 Percent confidence interval - lower         0.119       0.094\n  90 Percent confidence interval - upper         0.181       0.146\n  P-value H_0: RMSEA <= 0.050                    0.000       0.000\n  P-value H_0: RMSEA >= 0.080                    1.000       0.994\n                                                                  \n  Robust RMSEA                                               0.146\n  90 Percent confidence interval - lower                     0.109\n  90 Percent confidence interval - upper                     0.186\n  P-value H_0: Robust RMSEA <= 0.050                         0.000\n  P-value H_0: Robust RMSEA >= 0.080                         0.998\n\nStandardized Root Mean Square Residual:\n\n  SRMR                                           0.032       0.032\n\nParameter Estimates:\n\n  Standard errors                             Sandwich\n  Information bread                           Observed\n  Observed information based on                Hessian\n\nLatent Variables:\n                   Estimate  Std.Err  z-value  P(>|z|)   Std.lv  Std.all\n  SOP =~                                                                \n    SOP_1             0.897    0.034   26.031    0.000    0.897    0.816\n    SOP_2             1.087    0.033   32.881    0.000    1.087    0.874\n    SOP_3             0.921    0.034   26.776    0.000    0.921    0.819\n    SOP_4             1.052    0.032   32.503    0.000    1.052    0.871\n    SOP_5             0.782    0.042   18.532    0.000    0.782    0.653\n\nVariances:\n                   Estimate  Std.Err  z-value  P(>|z|)   Std.lv  Std.all\n   .SOP_1             0.405    0.032   12.713    0.000    0.405    0.335\n   .SOP_2             0.366    0.040    9.052    0.000    0.366    0.236\n   .SOP_3             0.415    0.038   10.900    0.000    0.415    0.328\n   .SOP_4             0.352    0.039    9.049    0.000    0.352    0.241\n   .SOP_5             0.824    0.052   15.898    0.000    0.824    0.574\n    SOP               1.000                               1.000    1.000\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlavaangui::plot_lavaan(fit_1f)\n```\n:::\n\n\n## Model Fit\n\n### Modification Indices\n\nModification indices (MI) flag parameters whose addition would most improve model fit. For a unidimensional model, the most commonly suggested modifications are **residual covariances** between pairs of items: these indicate item-specific shared variance beyond the common factor (e.g., similar wording, shared method).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodindices(fit_1f, sort. = TRUE, minimum.value = 5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     lhs op   rhs     mi    epc sepc.lv sepc.all sepc.nox\n12 SOP_1 ~~ SOP_2 55.350  0.190   0.190    0.494    0.494\n15 SOP_1 ~~ SOP_5 23.431 -0.137  -0.137   -0.238   -0.238\n16 SOP_2 ~~ SOP_3 22.901 -0.125  -0.125   -0.321   -0.321\n14 SOP_1 ~~ SOP_4 17.579 -0.104  -0.104   -0.276   -0.276\n21 SOP_4 ~~ SOP_5 11.492  0.099   0.099    0.183    0.183\n19 SOP_3 ~~ SOP_4 10.477  0.082   0.082    0.215    0.215\n20 SOP_3 ~~ SOP_5  6.605  0.074   0.074    0.127    0.127\n```\n\n\n:::\n:::\n\n\n::: {.callout-note}\nAn MI $\\geq 10$ (with $|epc| \\geq 0.10$ and theoretical justification) is a common threshold for considering a modification. Adding residual covariances post hoc is exploratory and should be cross-validated or justified on substantive grounds.\n:::\n\n### Correlation Residuals\n\n\n::: {.cell}\n\n```{.r .cell-code}\nres_cor <- lavResiduals(fit_1f, type = \"cor\")$cov\nnv_res  <- nrow(res_cor)\nbg_res  <- rgb(as.integer(res_cor > 0), 0, as.integer(res_cor < 0),\n               alpha = abs(res_cor))\nbg_res[upper.tri(res_cor, diag = TRUE) | abs(res_cor) <= 0.1] <- NA\nres_df <- as.data.frame(round(res_cor, 3))\ntinytable::tt(cbind(\" \" = rownames(res_df), res_df)) |>\n  tinytable::style_tt(i = 1:nv_res, j = 1:nv_res + 1, background = bg_res)\n```\n\n::: {.cell-output-display}\n\n```{=typst}\n#show figure: set block(breakable: true)\n\n#block[ // start block\n\n  #let style-dict = (\n    // tinytable style-dict after\n  )\n\n  #let style-array = ( \n    // tinytable cell style after\n  )\n\n  // Helper function to get cell style\n  #let get-style(x, y) = {\n    let key = str(y) + \"_\" + str(x)\n    if key in style-dict { style-array.at(style-dict.at(key)) } else { none }\n  }\n\n  // tinytable align-default-array before\n  #let align-default-array = ( left, left, left, left, left, left, ) // tinytable align-default-array here\n  #show table.cell: it => {\n    if style-array.len() == 0 { return it }\n    \n    let style = get-style(it.x, it.y)\n    if style == none { return it }\n    \n    let tmp = it\n    if (\"fontsize\" in style) { tmp = text(size: style.fontsize, tmp) }\n    if (\"color\" in style) { tmp = text(fill: style.color, tmp) }\n    if (\"indent\" in style) { tmp = pad(left: style.indent, tmp) }\n    if (\"underline\" in style) { tmp = underline(tmp) }\n    if (\"italic\" in style) { tmp = emph(tmp) }\n    if (\"bold\" in style) { tmp = strong(tmp) }\n    if (\"mono\" in style) { tmp = math.mono(tmp) }\n    if (\"strikeout\" in style) { tmp = strike(tmp) }\n    if (\"smallcaps\" in style) { tmp = smallcaps(tmp) }\n    tmp\n  }\n\n  #align(center, [\n\n  #table( // tinytable table start\n    columns: (auto, auto, auto, auto, auto, auto),\n    stroke: none,\n    rows: auto,\n    align: (x, y) => {\n      let style = get-style(x, y)\n      if style != none and \"align\" in style { style.align } else { left }\n    },\n    fill: (x, y) => {\n      let style = get-style(x, y)\n      if style != none and \"background\" in style { style.background }\n    },\n table.hline(y: 1, start: 0, end: 6, stroke: 0.05em + black),\n table.hline(y: 6, start: 0, end: 6, stroke: 0.08em + black),\n table.hline(y: 0, start: 0, end: 6, stroke: 0.08em + black),\n    // tinytable lines before\n\n    // tinytable header start\n    table.header(\n      repeat: true,\n[ ], [SOP_1], [SOP_2], [SOP_3], [SOP_4], [SOP_5],\n    ),\n    // tinytable header end\n\n    // tinytable cell content after\n[SOP_1], [0.000], [0.055], [-0.001], [-0.032], [-0.075],\n[SOP_2], [0.055], [0.000], [-0.035], [-0.008], [-0.017],\n[SOP_3], [-0.001], [-0.035], [0.000], [0.024], [0.039],\n[SOP_4], [-0.032], [-0.008], [0.024], [0.000], [0.041],\n[SOP_5], [-0.075], [-0.017], [0.039], [0.041], [0.000],\n\n    // tinytable footer after\n\n  ) // end table\n\n  ]) // end align\n\n] // end block\n```\n\n:::\n:::\n\n\n::: {.callout-note}\nColored cells show residual correlations > |0.10|. Large residuals identify pairs of items whose observed correlation is not well reproduced by the single-factor model.\n:::\n\n### Goodness of Fit\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlavaan::fitmeasures(fit_1f,\n  c(\"cfi.robust\", \"tli.robust\", \"rmsea.robust\",\n    \"rmsea.ci.lower.robust\", \"rmsea.ci.upper.robust\",\n    \"srmr\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           cfi.robust            tli.robust          rmsea.robust \n                0.967                 0.934                 0.146 \nrmsea.ci.lower.robust rmsea.ci.upper.robust                  srmr \n                0.109                 0.186                 0.032 \n```\n\n\n:::\n:::\n\n\n### Model Summary Table\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nglance_custom.lavaan <- function(x, ...) {\n  m <- lavaan::fitmeasures(x)\n  tibble::tibble(\n    cfi.robust   = m[[\"cfi.robust\"]],\n    tli.robust   = m[[\"tli.robust\"]],\n    rmsea.robust = m[[\"rmsea.robust\"]]\n  )\n}\n\ngm <- data.frame(\n  raw   = c(\"nobs\", \"statistic\", \"chi2.df\", \"p.chi2\",\n            \"cfi.robust\", \"tli.robust\", \"rmsea.robust\", \"srmr\"),\n  clean = c(\"N\", \"Chisq\", \"df\", \"p(Chisq)\",\n            \"CFI*\", \"TLI*\", \"RMSEA*\", \"SRMR\"),\n  fmt   = c(0, 2, 0, 3, 3, 3, 3, 3)\n)\nmodelsummary::msummary(\n    list(\"1-Factor\" = fit_1f),\n    fmt = fmt_decimal(digits = 2),\n    estimate = \"{estimate} [{conf.low}, {conf.high}]\",\n    statistic = NULL,\n    metrics = \"all\",\n    gof_map = gm\n)\n```\n\n::: {.cell-output-display}\n\n```{=typst}\n#show figure: set block(breakable: true)\n\n#block[ // start block\n\n  #let style-dict = (\n    // tinytable style-dict after\n    \"0_1\": 0, \"1_1\": 0, \"2_1\": 0, \"3_1\": 0, \"4_1\": 0, \"5_1\": 0, \"6_1\": 0, \"7_1\": 0, \"8_1\": 0, \"9_1\": 0, \"10_1\": 0, \"11_1\": 0, \"12_1\": 0, \"13_1\": 0, \"0_0\": 1, \"1_0\": 1, \"2_0\": 1, \"3_0\": 1, \"4_0\": 1, \"5_0\": 1, \"6_0\": 1, \"7_0\": 1, \"8_0\": 1, \"9_0\": 1, \"10_0\": 1, \"11_0\": 1, \"12_0\": 1, \"13_0\": 1\n  )\n\n  #let style-array = ( \n    // tinytable cell style after\n    (align: center,),\n    (align: left,),\n  )\n\n  // Helper function to get cell style\n  #let get-style(x, y) = {\n    let key = str(y) + \"_\" + str(x)\n    if key in style-dict { style-array.at(style-dict.at(key)) } else { none }\n  }\n\n  // tinytable align-default-array before\n  #let align-default-array = ( left, left, ) // tinytable align-default-array here\n  #show table.cell: it => {\n    if style-array.len() == 0 { return it }\n    \n    let style = get-style(it.x, it.y)\n    if style == none { return it }\n    \n    let tmp = it\n    if (\"fontsize\" in style) { tmp = text(size: style.fontsize, tmp) }\n    if (\"color\" in style) { tmp = text(fill: style.color, tmp) }\n    if (\"indent\" in style) { tmp = pad(left: style.indent, tmp) }\n    if (\"underline\" in style) { tmp = underline(tmp) }\n    if (\"italic\" in style) { tmp = emph(tmp) }\n    if (\"bold\" in style) { tmp = strong(tmp) }\n    if (\"mono\" in style) { tmp = math.mono(tmp) }\n    if (\"strikeout\" in style) { tmp = strike(tmp) }\n    if (\"smallcaps\" in style) { tmp = smallcaps(tmp) }\n    tmp\n  }\n\n  #align(center, [\n\n  #table( // tinytable table start\n    columns: (auto, auto),\n    stroke: none,\n    rows: auto,\n    align: (x, y) => {\n      let style = get-style(x, y)\n      if style != none and \"align\" in style { style.align } else { left }\n    },\n    fill: (x, y) => {\n      let style = get-style(x, y)\n      if style != none and \"background\" in style { style.background }\n    },\n table.hline(y: 1, start: 0, end: 2, stroke: 0.05em + black),\n table.hline(y: 6, start: 0, end: 2, stroke: 0.05em + black),\n table.hline(y: 14, start: 0, end: 2, stroke: 0.08em + black),\n table.hline(y: 0, start: 0, end: 2, stroke: 0.08em + black),\n    // tinytable lines before\n\n    // tinytable header start\n    table.header(\n      repeat: true,\n[ ], [1\\-Factor],\n    ),\n    // tinytable header end\n\n    // tinytable cell content after\n[SOP \\=~ SOP\\_1], [0.90 \\[0.83, 0.96\\]],\n[SOP \\=~ SOP\\_2], [1.09 \\[1.02, 1.15\\]],\n[SOP \\=~ SOP\\_3], [0.92 \\[0.85, 0.99\\]],\n[SOP \\=~ SOP\\_4], [1.05 \\[0.99, 1.12\\]],\n[SOP \\=~ SOP\\_5], [0.78 \\[0.70, 0.86\\]],\n[N], [575],\n[Chisq], [68.76],\n[df], [5],\n[p(Chisq)], [0.000],\n[CFI\\*], [0.967],\n[TLI\\*], [0.934],\n[RMSEA\\*], [0.146],\n[SRMR], [0.032],\n\n    // tinytable footer after\n\n  ) // end table\n\n  ]) // end align\n\n] // end block\n```\n\n:::\n:::\n\n\n::: {.callout-note}\n\\* CFI, TLI, and RMSEA use the Yuan–Bentler $T_2^*$ robust correction (`.robust`), preferred over the Satorra–Bentler `.scaled` variants (Savalei & Rosseel, 2023).\n:::\n\n## Composite Reliability\n\nComposite reliability (McDonald's $\\omega$) for the SOP scale:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsemTools::compRelSEM(fit_1f)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$SOP\n\nComposite `SOP` is composed of observed variables:\n\tSOP_1, SOP_2, SOP_3, SOP_4, SOP_5\nTrue-score variance is represented by common factor(s):\n\tSOP\nTotal variance of composite `SOP` determined from the unrestricted model.\nThe proportion attributable to \"true\" scores is its model-based estimate of reliability (\"omega\"):\n\n[1] 0.905\n```\n\n\n:::\n:::\n\n\n## Reporting\n\n### Sample Write-up\n\n**Method (Measures and Analysis)**\n\n> Self-oriented perfectionism was assessed with five items from the SOP scale (Williams & Edwards, 2021), rated on a 5-point Likert scale. We fit a unidimensional confirmatory factor analysis (CFA) model using the `lavaan` package (v0.6.21; Rosseel, 2012) in R. The latent factor variance was fixed to 1 for identification (`std.lv = TRUE`). To account for mild non-normality in the item responses, we used robust maximum likelihood estimation (MLR) with Yuan–Bentler scaled standard errors and a Satorra–Bentler scaled $\\chi^2$ test statistic. Missing data were handled with full information maximum likelihood (FIML). Model fit was evaluated using the robust CFI ($\\geq .95$), robust RMSEA ($\\leq .06$), and SRMR ($\\leq .08$; Hu & Bentler, 1999). Composite reliability was estimated using McDonald's $\\omega$ via `semTools::compRelSEM()`.\n\n**Results**\n\n> The hypothesized unidimensional CFA model showed acceptable fit to the data, robust $\\chi^2$(5) = 45.71, $p$ < .001, robust CFI = 0.967, robust RMSEA = 0.146, 90% CI [0.109, 0.186], SRMR = 0.032. Inspection of modification indices and correlation residuals did not reveal any theoretically justified model modifications. All five items loaded significantly on the SOP factor, with standardized loadings ranging from 0.65 to 0.87. Composite reliability was $\\omega$ = 0.905, indicating good internal consistency.\n\n## References\n\nWilliams, M. N., & Edwards, S. R. (2021). Conceptual replication of Seo (2008): Self-efficacy as a mediator in the relationship between self-oriented perfectionism and academic procrastination. *Current Issues in Personality Psychology*, *10*(2), 98–111. <https://doi.org/10.5114/cipp.2021.110948>\n\nKline, R. B. (2023). *Principles and practice of structural equation modeling* (5th ed.). Guilford Press.\n\nSavalei, V., & Rosseel, Y. (2023). Computational options for standard errors and test statistics with incomplete normal and nonnormal data in SEM. *Structural Equation Modeling*, *30*(2), 171–185. <https://doi.org/10.1080/10705511.2022.2141754>\n\nSeo, E. H. (2008). Self-efficacy as a mediator in the relationship between self-oriented perfectionism and academic procrastination. *Social Behavior and Personality*, *36*(6), 753–764. <https://doi.org/10.2224/sbp.2008.36.6.753>\n",
    "supporting": [
      "cfa_files/figure-typst"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}